### PR TITLE
Fix readability + minor semantic issues in Python files

### PR DESCRIPTION
**Pull request by nnmm**
This is only a separate PR to make the diff smaller. I know style changes are not needed yet, but this took five minutes and I was waiting anyway for things to compile.

* Removed `#!/usr/bin/env python`, it is not needed for libraries at all and even for the executable, `ros2 run` takes care of selecting the interpreter
* Fixed lint issues pointed out by `flake8` and ran `isort`
* Changed double underscores to single underscores since [double underscores have special meaning in Python](https://dbader.org/blog/meaning-of-underscores-in-python).

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@nnmm The code looks good to me. Did you confirm this script runs correctly?

**Comment by nnmm** [comment]
@TakaHoribe Yes, I ran the script and it looks fine.

**Review by TakaHoribe — APPROVED** [review]
Thanks! Then, let's merge.

**Comment by TakaHoribe** [comment]
@nnmm Can we merge this now, or better to wait until the #2 is merged?

**Comment by nnmm** [comment]
@TakaHoribe it can be merged now.

**Pull request merged**
